language: node_js
node_js:
  - "10.15.3"
install:
  - yarn install
script:
  - yarn ci
before_script:
  - yarn build
after_script:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
